pipeline {
	agent any
	
	environment {
		GIT_REPOSITORY = "https://github.com/jessbdeakin/SIT223-Task6.2C.git"
		GIT_BRANCH = "main"

		EMAIL_ADDRESS = "s222317449@deakin.edu.au"

		BUILD_PATH = '/build'
	}

	stages {
		stage('Build') {
			steps {

				echo "Fetch source code"
				git branch: "${GIT_BRANCH}", url: "${GIT_REPOSITORY}"

				echo 'Build code with Gradle'
				// bat 'gradle clean build'
			}
		}
		
		stage('Unit and Integration Tests') {
			steps {
				echo 'Run unit tests generated by Google Test framework'
				// bat ''

				mail to: "${EMAIL_ADDRESS}", subject: "[JENKINS] Successful test", body: ""
			}
			post {
				failure {
					mail to: "${EMAIL_ADDRESS}", subject: "[JENKINS] Failed test", body: ""
				}
			}
		}
		
		stage('Code Analysis'){
			steps {
				echo 'Perform code analysis with Cppcheck'
				// bat 'cppcheck %BUILD_PATH% 2> cppcheck.xml'
			}
		}
		  
		stage('Security Scan'){
			steps {
				echo 'Security scan.'

				mail to: "${EMAIL_ADDRESS}", subject: "[JENKINS] Successful security scan", body: ""
			}
			post {
				failure {
					mail to: "${EMAIL_ADDRESS}", subject: "[JENKINS] Failed security scan", body: ""
				}
			}
		}
		
		stage('Deploy to Staging'){
			steps {
				echo "Deploy the app to testing environment ${TESTING_ENVIRONMENT}"
			}
		}
		
		stage('Integration Tests on Staging'){
			steps {
				sleep(10)
			}
		}
		
		stage('Deploy to Production'){
			steps {
				echo "Deploy the app to production environment ${PRODUCTION_ENVIRONMENT}"
			}
		}
	}
}
